# 蚂蚁财富
- package_name: com.antfortune.wealth
  max_click_count: 1
  skip_bounds:
    - 1440,3024#1139,224,1370,315

# 酷安
- package_name: com.coolapk.market
  skip_id: com.byted.pangle.m:id/tt_splash_skip_btn
  skip_bounds:
    - 1440,3024#1116,219,1332,316

# 支付宝
- package_name: com.eg.android.AlipayGphone
  max_click_count: 0

# Github
- package_name: com.github.android
  max_click_count: 0

# 京东阅读
- package_name: com.jd.app.reader
  skip_bounds:
    - 1440,3024#1209,113,1338,165

# 铁路12306
- package_name: com.MobileTicket
  skip_id: com.MobileTicket:id/tv_skip

# 爱奇艺
- package_name: com.qiyi.video
  skip_text: 关闭

# 爱奇艺极速版
- package_name: com.qiyi.video.lite 
  skip_text: 关闭

# 腾讯微云
- package_name: com.qq.qcloud
  skip_id: com.qq.qcloud:id/gdt_ad_text
  skip_bounds:
    - 1440,3024#1223,196,1384,308

# 夸克
- package_name: com.quark.browser
  max_click_count: 0

# 微信
- package_name: com.tencent.mm
  max_click_count: 0

# 华为时钟
- package_name: com.huawei.deskclock
  max_click_count: 0